spring:
  profiles:
    active: 
    - dev 
---
spring:
  profiles: dev #开发环境
  applicaiton: 
    name: microservicecloud-config-atguigu-dev
---
spring: 
  profilese: test #测试环境
  application:  
    name: microservicecloud-config-atguigu-test
    #请以UTF-8格式保存